customhost="studentdb.cvqofr3thjhc.us-east-1.rds.amazonaws.com"
customuser="admin"
custompass="12345678"
customdb="studentdb"
custombucket="my-bucket-11294"
# customregion=""
admin_name="Admin"
admin_pass="myadmin123"
